# as explained here -http://www.mpcdf.mpg.de/services/computing/draco/filesystems - 
# and when you login to draco, you set your tmp folder to the distributed file system
export TMPDIR=/ptmp/$USER

module load git

# shorten you PS1 to show:
# [<draco node number>:<current directory to 30 char>]
PROMPT_COMMAND='DIR=`pwd|sed -e "s!$HOME!~!"`; if [ ${#DIR} -gt 30 ]; then CurDir=${DIR:0:12}...${DIR:${#DIR}-15}; else CurDir=$DIR; fi'
PS1="[\h:\$CurDir] \$ "

# load the software installed by the bioinformatics core facility of the MPI AGE
source /u/jboucas/age-bioinformatics.rc

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

